#!/usr/bin/env node
/**
 * Publishes @open-wallet-standard/core packages to npm.
 *
 * Builds the native module for the current platform, copies the binary
 * into the right npm/<platform> directory, and publishes both the
 * platform package and the main package.
 *
 * Usage:
 *   node publish.mjs            # publish
 *   node publish.mjs --dry-run  # preview without publishing
 */

import { execSync } from 'node:child_process';
import { copyFileSync, existsSync, readdirSync } from 'node:fs';
import { join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const dryRun = process.argv.includes('--dry-run');
const flag = dryRun ? '--dry-run' : '';

function run(cmd, opts = {}) {
  console.log(`\x1b[1;34m==>\x1b[0m ${cmd}`);
  return execSync(cmd, { stdio: 'inherit', cwd: __dirname, ...opts });
}

function info(msg) {
  console.log(`\x1b[1;34m==>\x1b[0m ${msg}`);
}

// 1. Build the native module
run('npx napi build --platform --release');

// 2. Find the built .node file and copy it to the right npm/ directory
const nodeFile = readdirSync(__dirname).find((f) => f.endsWith('.node'));
if (!nodeFile) {
  console.error('No .node binary found after build');
  process.exit(1);
}

// e.g. "ows-node.darwin-arm64.node" → "darwin-arm64"
const platform = nodeFile.replace('ows-node.', '').replace('.node', '');
const platformDir = join(__dirname, 'npm', platform);

if (!existsSync(platformDir)) {
  console.error(`Platform directory npm/${platform} does not exist`);
  process.exit(1);
}

const dest = join(platformDir, nodeFile);
copyFileSync(join(__dirname, nodeFile), dest);
info(`Copied ${nodeFile} → npm/${platform}/`);

// 3. Publish the platform package
run(`npm publish ${flag} --access public`, { cwd: platformDir });

// 4. Publish the main package (index.js + index.d.ts are already generated by the build)
run(`npm publish ${flag} --access public`);

console.log('\n\x1b[1;32mDone!\x1b[0m');
